---

name: 🐞 Bug report
description: Create a bug report to help us improve AdGuard Browser Extension.
labels: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: app_version
    attributes:
      label: AdGuard Extension version
      description: What version of our extension are you running?
      placeholder: For example, 4.1.22 beta
    validations:
      required: true
  - type: input
    id: br_version
    attributes:
      label: Browser version
      description: What browser do you use?
      placeholder: For example, Chrome 106
    validations:
      required: true
  - type: input
    id: os_version
    attributes:
      label: OS version
      description: What operating system do you use?
      placeholder: For example, macOS 12.4
    validations:
      required: true
  - type: dropdown
    id: filters
    attributes:
      label: What filters do you have enabled?
      description: |
        Select enabled filters from the list if they are related to the extension bug.
        If the issue is related to the filtering (missed ads, cookie, etc.)
        use the [Web Reporting Tool](https://kb.adguard.com/en/technical-support/reporting-tool) please.
      multiple: true
      options:
        - No filters
        - AdGuard Base filter
        - AdGuard Mobile Ads filter
        - AdGuard Chinese filter
        - AdGuard Dutch filter
        - AdGuard French filter
        - AdGuard German filter
        - AdGuard Japanese filter
        - AdGuard Russian filter
        - AdGuard Spanish/Portuguese filter
        - AdGuard Turkish filter
        - AdGuard Tracking Protection filter
        - AdGuard URL Tracking filter
        - AdGuard Social Media filter
        - AdGuard Annoyances filter
        - AdGuard Cookie Notices filter
        - AdGuard Popups filter
        - AdGuard Mobile App Banners filter
        - AdGuard Widgets filter
        - AdGuard Other Annoyances filter
        - AdGuard DNS filter
        - AdGuard Experimental filter
        - Filter unblocking search ads and self-promotion
        - ---Third-party filters---
        - EasyList
        - ABPindo
        - Bulgarian list
        - EasyList China
        - EasyList Czech and Slovak
        - EasyList Dutch
        - EasyList Germany
        - EasyList Hebrew
        - EasyList Italy
        - EasyList Lithuania
        - Latvian List
        - Liste AR
        - Liste FR
        - ROList
        - EasyPrivacy
        - Icelandic ABP List
        - AdBlockID
        - Greek AdBlock Filter
        - Fanboy's Annoyances
        - Fanboy's Social Blocking List
        - Web Annoyances Ultralist
        - Thai Ads Filters
        - Hungarian filter
        - Peter Lowe's Blocklist
        - Xfiles
        - Adblock Warning Removal List
        - Online Malicious URL Blocklist
        - RU AdList - Counters
        - ABPVN List
        - Fanboy's Enhanced Tracking List
        - Official Polish filters for AdBlock, uBlock Origin & AdGuard
        - Polish GDPR-Cookies Filters
        - Estonian List
        - CJX's Annoyances List
        - Polish Social Filters
        - Fanboy's Anti-Facebook List
        - List-KR
        - xinggsf
        - I don't care about cookies
        - EasyList Spanish
        - KAD - Anti-Scam
        - Adblock List for Finland
        - ROLIST2
        - Iranian filter
        - road-block
        - Polish Annoyances Filters
        - Polish Anti Adblock Filters
        - Fanboy's Anti-thirdparty Fonts
        - EasyList Cookie List
        - NoCoin Filter List
        - Frellwit's Swedish Filter
        - YousList
        - AlleBlock
        - EasyList Polish
        - Polish Anti-Annoying Special Supplement
        - Dandelion Sprout's Nordic Filters
        - Dandelion Sprout's Annoyances List
        - Legitimate URL Shortener
        - Dandelion Sprout's Serbo-Croatian List
        - IndianList
        - Others
    validations:
      required: false
  - type: dropdown
    id: stealth
    attributes:
      label: What Stealth Mode options do you have enabled?
      description: Select any of these options if you have them enabled in Stealth Mode.
      multiple: true
      options:
        - Block trackers
        - Remove tracking parameters
        - Hide your search queries
        - Send websites signals not to track you
        - Self-destruction of third-party cookies
        - Self-destruction of first-party cookies
        - Hide Referrer from third parties
        - Remove X-Client-Data header
        - Disable WebRTC
  - type: textarea
    id: what-happened
    attributes:
      label: Issue Details
      description: What happened?
      placeholder: Please include all relevant details about the issue you've experienced.
    validations:
      required: false
  - type: textarea
    id: how_it_should_be
    attributes:
      label: Expected Behavior
      description:
      placeholder: A clear and concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    id: screens
    attributes:
      label: Screenshots
      description: |
        If applicable add screenshots explaining your problem.
        You can drag and drop images or paste them from clipboard.
        Use `<details> </details>` tag to hide screenshots under the spoiler.
      placeholder: If applicable add screenshots explaining your problem.
      value: |
          <details><summary>Screenshot 1:</summary>

          <!-- paste screenshot here -->

          </details>
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description:
      placeholder: Add any other context about the problem here.
    validations:
      required: false
