(function () {
var _g = window._g;
if (!_g) return;
_g.r("trusted-click-element", {"name":"trusted-click-element","args":["ytd-consent-bump-v2-lightbox .eom-buttons > .ytd-consent-bump-v2-lightbox > .ytd-consent-bump-v2-lightbox button.ytSpecButtonShapeNextHost"],"engine":"extension","version":"2.4.2","verbose":false}, ["ytd-consent-bump-v2-lightbox .eom-buttons > .ytd-consent-bump-v2-lightbox > .ytd-consent-bump-v2-lightbox button.ytSpecButtonShapeNextHost"], "9c6c2461437a222172a5c932664b31f7");
_g.r("trusted-click-element", {"name":"trusted-click-element","args":["ytd-consent-bump-v2-lightbox .eom-buttons > .ytd-consent-bump-v2-lightbox > .ytd-consent-bump-v2-lightbox button.yt-spec-button-shape-next"],"engine":"extension","version":"2.4.2","verbose":false}, ["ytd-consent-bump-v2-lightbox .eom-buttons > .ytd-consent-bump-v2-lightbox > .ytd-consent-bump-v2-lightbox button.yt-spec-button-shape-next"], "1fd12adcfadeb42f00feaf2bebc382da");
_g.r("trusted-click-element", {"name":"trusted-click-element","args":["ytm-consent-bump-v2-renderer .dialog-scrollable-content > .one-col-dialog-buttons > ytm-button-renderer.eom-reject button.ytSpecButtonShapeNextHost","","2000"],"engine":"extension","version":"2.4.2","verbose":false}, ["ytm-consent-bump-v2-renderer .dialog-scrollable-content > .one-col-dialog-buttons > ytm-button-renderer.eom-reject button.ytSpecButtonShapeNextHost","","2000"], "816a72664579ac18edb5f14c3ed582f6");
_g.r("trusted-click-element", {"name":"trusted-click-element","args":["ytm-consent-bump-v2-renderer .dialog-scrollable-content > .one-col-dialog-buttons > ytm-button-renderer.eom-reject button.yt-spec-button-shape-next","","2000"],"engine":"extension","version":"2.4.2","verbose":false}, ["ytm-consent-bump-v2-renderer .dialog-scrollable-content > .one-col-dialog-buttons > ytm-button-renderer.eom-reject button.yt-spec-button-shape-next","","2000"], "471c2de3f48a70706f985258fee1802e");
_g.r("trusted-click-element", {"name":"trusted-click-element","args":["form[action=\"https://consent.youtube.com/save\"][jsaction] button[jsname=\"b3VHJd\"]"],"engine":"extension","version":"2.4.2","verbose":false}, ["form[action=\"https://consent.youtube.com/save\"][jsaction] button[jsname=\"b3VHJd\"]"], "643b2d3f6e8b7a8f66b636c7e7d25276");
})();
