---
version: 2
plan:
  project-key: ADGEXT
  key: AUTOBUILD
  name: browser extension - auto-build
variables:
  # Playwright is needed for integration tests after build.
  dockerPlaywright: adguard/playwright-runner:22.17--1.53.2--1
  # Node.js is needed for build and tests.
  dockerNode: adguard/extension-builder:22.17--0.3.0--0
  # Stable branch name for auto-update only filters.
  stableBranchName: stable/v5.2

# Since auto-builds are being run only for a stable branch now (specified in
# `bamboo.stableBranchName`) we should skip the build stage for other branches.
stages:
  - Do nothing:
      manual: false
      final: false
      jobs:
        - Do nothing

Do nothing: !include 'jobs/auto-builds/do-nothing.yaml'

branches:
  create: manually
  delete: never
  link-to-jira: true

notifications:
  - recipients:
      - webhook:
          name: Build webhook
          url: http://prod.jirahub.service.eu.consul/v1/webhook/bamboo
    events:
      - plan-status-changed

labels: []

other:
  concurrent-build-plugin: system-default

# Run plan only for 'stable/v5.2' branch.
# Override is needed to skip the build stage for other branches,
# because even if branches are not supposed to be run for PRs
# (due to 'create: manually' above), build was triggered by 'cron' anyway.
branch-overrides:
  -
    # Note: it should be equal with `bamboo.stableBranchName`
    stable/v5.2:
      # Job definitions for auto-builds
      Check CWS Availability: !include 'jobs/auto-builds/check-cws-availability.yaml'
      Lint: !include 'jobs/auto-builds/lint.yaml'
      Unit tests: !include 'jobs/auto-builds/unit-tests.yaml'
      Update filters and build: !include 'jobs/auto-builds/update-filters-and-build.yaml'
      Integration tests: !include 'jobs/auto-builds/integration-tests.yaml'

      stages:
        # Note: we do this check inside build plan and not in deployment plan to
        # reduce extra complexity in publish scripts and because we suppose that
        # channels will not be changed between build and publish stages.
        - Check CWS Availability:
            manual: false
            final: false
            jobs:
              - Check CWS Availability
        - Tests:
            manual: false
            final: false
            jobs:
              - Lint
              - Unit tests
        - Update filters and build:
            manual: false
            final: false
            jobs:
              - Update filters and build
        - Integration tests:
            manual: false
            final: false
            jobs:
              - Integration tests

      # Run auto-build as specified and collect all changes made by
      # filter list maintainers.
      triggers:
        - cron:
            expression: 0 30 */12 ? * *
            description: Run auto-build every 12 hours at 30 minutes past the hour.
