---
version: 2
plan:
  project-key: ADGEXT
  key: BEFIREFOXBETASPECS
  name: browser extension - build firefox beta
  description: |
    Builds and signs Firefox beta extension via Mozilla. May fail on 20-min
    timeout if signing is slow.
    Do not stop manually. Re-run the SAME build after Mozilla signs it
    to download the signed .xpi.
stages:
  - Build:
      manual: false
      final: false
      jobs:
        - Build

Build:
  key: BUILD
  other:
    clean-working-dir: true
  tasks:
    - checkout:
        force-clean-build: true
    - script:
        interpreter: SHELL
        scripts:
          - |-
            # 'set' should be added to the beginning of each script to ensure that it runs with the correct options.
            #  -e: Exit immediately if any command exits with a non-zero status (i.e., if a command fails).
            #  -x: Print each command to the terminal as it is executed, which is useful for debugging.
            set -ex

            # Fix mixed logs
            exec 2>&1

            # Clone tsurlfilter to sibling directory (uses SSH from CI environment)
            ./bamboo-specs/scripts/clone-tsurlfilter.sh

            export DOCKER_BUILDKIT=1

            # Build Firefox beta artifacts (firefox.zip, source.zip, build.txt)
            docker build \
              --file Dockerfile \
              --progress plain \
              --build-arg TEST_RUN_ID=${bamboo.buildNumber} \
              --build-context tsurlfilter=../tsurlfilter \
              --target firefox-beta-build-output \
              --output type=local,dest=output \
              .

            # Sign Firefox extension with go-webext (firefox.xpi, update.json)
            # Uses artifacts from previous build step via named build context
            docker build \
              --file Dockerfile \
              --progress plain \
              --build-arg TEST_RUN_ID=${bamboo.buildNumber} \
              --build-arg FIREFOX_CLIENT_ID=${bamboo_firefoxAmoClientId} \
              --build-arg FIREFOX_CLIENT_SECRET=${bamboo_firefoxAmoClientSecret} \
              --build-context firefox-artifacts=output/artifacts \
              --target firefox-beta-sign-output \
              --output type=local,dest=output \
              .
    - inject-variables:
        file: output/artifacts/build.txt
        scope: RESULT
        namespace: inject
  final-tasks:
    - script:
        interpreter: SHELL
        scripts:
          - "./bamboo-specs/scripts/cleanup.sh output/artifacts/build.txt,output/artifacts/firefox.zip,output/artifacts/firefox.xpi,output/artifacts/update.json,output/artifacts/source.zip"
  artifacts:
    - name: build.txt
      location: output/artifacts
      pattern: build.txt
      shared: true
      required: true
    - name: firefox.zip
      location: output/artifacts
      pattern: firefox.zip
      shared: true
      required: true
    - name: firefox.xpi
      location: output/artifacts
      pattern: firefox.xpi
      shared: true
      required: true
    - name: update.json
      location: output/artifacts
      pattern: update.json
      shared: true
      required: true
    - name: source.zip
      location: output/artifacts
      pattern: source.zip
      shared: true
      required: true
  requirements:
    - extension: 'true'

triggers: []

branches:
  create: manually
  delete: never
  link-to-jira: 'true'

notifications:
  - events:
      - plan-status-changed
    recipients:
      - webhook:
          name: Build webhook
          url: http://prod.jirahub.service.eu.consul/v1/webhook/bamboo
labels: []
other:
  concurrent-build-plugin: system-default
