---
version: 2
plan:
  project-key: ADGEXT
  key: BEBETASPECS
  name: browser extension - build beta
variables:
  dockerNode: adguard/extension-builder:22.14--0.2--0
  # Possible size of change for the bundle and each entry point in percentage,
  # if more than specified value - Size Check stage will fail
  bundleSizeThreshold: '10'
stages:
  - Size Check:
      manual: 'false'
      final: 'false'
      jobs:
        - Check Bundle Size
  - Build:
      manual: 'false'
      final: 'false'
      jobs:
        - Build

Check Bundle Size:
  key: SIZECHECK
  other:
    clean-working-dir: true
  docker:
    image: ${bamboo.dockerNode}
    volumes:
      ${system.PNPM_DIR}: "${bamboo.cachePnpm}"
  tasks:
    - checkout:
        force-clean-build: 'true'
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -x
            set -e

            # Fix mixed logs
            exec 2>&1

            ls -la

            # Set cache directory
            pnpm config set store-dir ${bamboo.cachePnpm}

            # Install dependencies
            pnpm install ${bamboo.varsPnpm}

            # Determine build type based on plan name: if
            BUILD_TYPE="beta"
            if [[ "${bamboo.planKey}" == *RELEASE* ]]; then
              BUILD_TYPE="release"
            fi

            echo "Executing build for $BUILD_TYPE"

            # Run build
            pnpm $BUILD_TYPE

            # Create artifacts directory if it doesn't exist
            mkdir -p artifacts

            # Check bundle size with threshold from bamboo variable or default
            echo "Checking bundle sizes with threshold ${bamboo.bundleSizeThreshold:10}%"
            BUILD_TYPE=$BUILD_TYPE BUNDLE_SIZE_THRESHOLD=${bamboo.bundleSizeThreshold:10} pnpm check-bundle-size

            cp .bundle-sizes.json artifacts/bundle-sizes.json
  final-tasks:
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -x
            set -e

            # Fix mixed logs
            exec 2>&1

            ls -la

            echo "Size before cleanup:" && du -h | tail -n 1
            rm -rf node_modules build
            echo "Size after cleanup:" && du -h | tail -n 1
  artifacts:
    # For information and debug
    - name: bundle-sizes.json
      location: artifacts
      pattern: .bundle-sizes.json
      shared: false
      # TODO: Mark as required after merge to master
      # (this is needed to pass bamboo checks for artifacts chain)
      required: false
  requirements:
    - adg-docker: 'true'


Build:
  key: BUILD
  other:
    clean-working-dir: true
  docker:
    image: ${bamboo.dockerNode}
    volumes:
      ${system.PNPM_DIR}: "${bamboo.cachePnpm}"
  tasks:
    - checkout:
        force-clean-build: 'true'
    - checkout:
        repository: extensions-private
        path: private
        force-clean-build: 'true'
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -x
            set -e

            # Fix mixed logs
            exec 2>&1

            ls -la

            # Set cache directory
            pnpm config set store-dir ${bamboo.cachePnpm}

            pnpm install ${bamboo.varsPnpm}
            pnpm beta

            # Create artifacts directory if it doesn't exist
            mkdir -p artifacts

            # Copy all artifacts to the artifacts directory
            cp build/beta/build.txt artifacts/
            cp build/beta/chrome.zip artifacts/
            cp build/beta/chrome-mv3.zip artifacts/
            cp build/beta/edge.zip artifacts/
            cp build/beta/chrome.crx artifacts/
            cp build/beta/update.xml artifacts/
    - inject-variables:
        file: artifacts/build.txt
        scope: RESULT
        namespace: inject
    - any-task:
        plugin-key: com.atlassian.bamboo.plugins.vcs:task.vcs.tagging
        configuration:
          selectedRepository: defaultRepository
          tagName: v${bamboo.inject.version}-beta
  final-tasks:
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -x
            set -e

            # Fix mixed logs
            exec 2>&1

            ls -la

            echo "Size before cleanup:" && du -h | tail -n 1
            rm -rf node_modules build
            echo "Size after cleanup:" && du -h | tail -n 1
  artifacts:
    - name: build.txt
      location: artifacts
      pattern: build.txt
      shared: true
      required: true
    - name: chrome.zip
      location: artifacts
      pattern: chrome.zip
      shared: true
      required: true
    - name: chrome-mv3.zip
      location: artifacts
      pattern: chrome-mv3.zip
      shared: true
      required: true
    - name: edge.zip
      location: artifacts
      pattern: edge.zip
      shared: true
      required: true
    - name: chrome.crx
      location: artifacts
      pattern: chrome.crx
      shared: true
      required: true
    - name: update.xml
      location: artifacts
      pattern: update.xml
      shared: true
      required: true
  requirements:
    - adg-docker: 'true'

triggers: []

branches:
  create: manually
  delete: never
  link-to-jira: 'true'

notifications:
  - events:
      - plan-status-changed
    recipients:
      - webhook:
          name: Build webhook
          url: http://prod.jirahub.service.eu.consul/v1/webhook/bamboo
labels: []
other:
  concurrent-build-plugin: system-default
