---
version: 2
plan:
  project-key: ADGEXT
  key: BEBETASPECS
  name: browser extension - build beta
stages:
  - Size and locales check:
      manual: false
      final: false
      jobs:
        - Check Bundle Size
        - Check translations
  - Build:
      manual: false
      final: false
      jobs:
        - Build

Check Bundle Size:
  key: SIZECHECK
  other:
    clean-working-dir: true
  tasks:
    - checkout:
        force-clean-build: true
    - script:
        interpreter: SHELL
        scripts:
          - |-
            # 'set' should be added to the beginning of each script to ensure that it runs with the correct options.
            #  -e: Exit immediately if any command exits with a non-zero status (i.e., if a command fails).
            #  -x: Print each command to the terminal as it is executed, which is useful for debugging.
            set -ex

            # Fix mixed logs
            exec 2>&1

            # Clone tsurlfilter to sibling directory (uses SSH from CI environment)
            ./bamboo-specs/scripts/clone-tsurlfilter.sh

            export DOCKER_BUILDKIT=1

            # Build with named context for tsurlfilter
            # Docker checksums the context content for cache invalidation
            docker build \
              --file Dockerfile \
              --progress plain \
              --build-arg TEST_RUN_ID=${bamboo.buildNumber} \
              --build-context tsurlfilter=../tsurlfilter \
              --target bundle-size-check-output \
              --output type=local,dest=output \
              .
  final-tasks:
    - script: &cleanup-script
        interpreter: SHELL
        scripts:
          - "./bamboo-specs/scripts/cleanup.sh"
  requirements: &requirements
    - extension: 'true'

Check translations:
  key: LOCALESCHECK
  other:
    clean-working-dir: true
  tasks:
    - checkout:
        force-clean-build: true
    - script:
        interpreter: SHELL
        scripts:
          - |-
            # 'set' should be added to the beginning of each script to ensure that it runs with the correct options.
            #  -e: Exit immediately if any command exits with a non-zero status (i.e., if a command fails).
            #  -x: Print each command to the terminal as it is executed, which is useful for debugging.
            set -ex

            # Fix mixed logs
            exec 2>&1

            # Clone tsurlfilter to sibling directory (uses SSH from CI environment)
            ./bamboo-specs/scripts/clone-tsurlfilter.sh

            export DOCKER_BUILDKIT=1

            # Build with named context for tsurlfilter
            # Docker checksums the context content for cache invalidation
            docker build \
              --file Dockerfile \
              --progress plain \
              --build-arg TEST_RUN_ID=${bamboo.buildNumber} \
              --build-context tsurlfilter=../tsurlfilter \
              --target locales-check-output \
              --output type=local,dest=output \
              .
  final-tasks:
    - script: *cleanup-script
  requirements: *requirements

Build:
  key: BUILD
  other:
    clean-working-dir: true
  tasks:
    - checkout:
        force-clean-build: true
    - checkout:
        repository: extensions-private
        path: private
        force-clean-build: true
    - script:
        interpreter: SHELL
        scripts:
          - |-
            # 'set' should be added to the beginning of each script to ensure that it runs with the correct options.
            #  -e: Exit immediately if any command exits with a non-zero status (i.e., if a command fails).
            #  -x: Print each command to the terminal as it is executed, which is useful for debugging.
            set -ex

            # Fix mixed logs
            exec 2>&1

            # Clone tsurlfilter to sibling directory (uses SSH from CI environment)
            ./bamboo-specs/scripts/clone-tsurlfilter.sh

            export DOCKER_BUILDKIT=1

            # Build beta artifacts (chrome, chrome-mv3, edge zips + build.txt)
            docker build \
              --file Dockerfile \
              --progress plain \
              --build-arg TEST_RUN_ID=${bamboo.buildNumber} \
              --build-context tsurlfilter=../tsurlfilter \
              --build-context private=private \
              --target beta-build-output \
              --output type=local,dest=output \
              .

            # Build beta CRX and update.xml
            docker build \
              --file Dockerfile \
              --progress plain \
              --build-arg TEST_RUN_ID=${bamboo.buildNumber} \
              --build-context tsurlfilter=../tsurlfilter \
              --build-context private=private \
              --target beta-chrome-crx-output \
              --output type=local,dest=output \
              .
    - inject-variables:
        file: output/artifacts/build.txt
        scope: RESULT
        namespace: inject
    - any-task:
        plugin-key: com.atlassian.bamboo.plugins.vcs:task.vcs.tagging
        configuration:
          selectedRepository: defaultRepository
          tagName: v${bamboo.inject.version}-${bamboo.buildType}
  final-tasks:
    - script:
        interpreter: SHELL
        scripts:
          - "./bamboo-specs/scripts/cleanup.sh output/artifacts/build.txt,output/artifacts/chrome.zip,output/artifacts/chrome-mv3.zip,output/artifacts/edge.zip,output/artifacts/chrome.crx,output/artifacts/update.xml"
  artifacts:
    - name: build.txt
      location: output/artifacts
      pattern: build.txt
      shared: true
      required: true
    - name: chrome.zip
      location: output/artifacts
      pattern: chrome.zip
      shared: true
      required: true
    - name: chrome-mv3.zip
      location: output/artifacts
      pattern: chrome-mv3.zip
      shared: true
      required: true
    - name: edge.zip
      location: output/artifacts
      pattern: edge.zip
      shared: true
      required: true
    - name: chrome.crx
      location: output/artifacts
      pattern: chrome.crx
      shared: true
      required: true
    - name: update.xml
      location: output/artifacts
      pattern: update.xml
      shared: true
      required: true
  requirements: *requirements

triggers: []

branches:
  create: manually
  delete: never
  link-to-jira: 'true'

notifications:
  - events:
      - plan-status-changed
    recipients:
      - webhook:
          name: Build webhook
          url: http://prod.jirahub.service.eu.consul/v1/webhook/bamboo
labels: []
other:
  concurrent-build-plugin: system-default
