---
version: 2
plan:
  project-key: ADGEXT
  key: BEFIREFOXBETASPECS
  name: browser extension - build firefox beta
variables:
  dockerNode: adguard/extension-builder:18.19.0--0.1.3
stages:
  - Build:
      manual: 'false'
      final: 'false'
      jobs:
        - Build

Build:
  key: BUILD
  other:
    clean-working-dir: true
  docker:
    image: ${bamboo.dockerNode}
    volumes:
      ${system.PNPM_DIR}: "${bamboo.cachePnpm}"
    # we use dns to avoid etimedout error when AMO is validating extension
    docker-run-arguments: ['--dns', '8.8.8.8']
  tasks:
    - checkout:
        force-clean-build: 'true'
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -x
            set -e

            # Fix mixed logs
            exec 2>&1

            ls -la

            # Set cache directory
            pnpm config set store-dir ${bamboo.cachePnpm}

            pnpm install ${bamboo.varsPnpm}
            pnpm beta firefox-standalone

            # zip source files for publishing on AMO
            git ls-files | zip -@ build/beta/source.zip

            # Move to the build/beta directory and sign the Firefox extension
            cd ./build/beta

            # Set environment variables and run go-webext to sign the Firefox extension
            FIREFOX_CLIENT_ID="${bamboo_firefoxAmoClientId}" \
            FIREFOX_CLIENT_SECRET="${bamboo_firefoxAmoClientSecret}" \
            go-webext -v sign firefox -f 'firefox.zip' -s 'source.zip' -o 'firefox.xpi'

            # Exit from build/beta directory
            cd ../..

            # Create artifacts directory if it doesn't exist
            mkdir -p artifacts

            # Copy all artifacts to the artifacts directory
            cp build/beta/build.txt artifacts/
            cp build/beta/firefox.zip artifacts/
            cp build/beta/firefox.xpi artifacts/
            cp build/beta/update.json artifacts/
            cp build/beta/source.zip artifacts/
    - inject-variables:
        file: artifacts/build.txt
        scope: RESULT
        namespace: inject
  final-tasks:
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -x
            set -e

            # Fix mixed logs
            exec 2>&1

            ls -la

            echo "Size before cleanup:" && du -h | tail -n 1
            rm -rf node_modules build
            echo "Size after cleanup:" && du -h | tail -n 1
  artifacts:
    - name: build.txt
      location: artifacts
      pattern: build.txt
      shared: true
      required: true
    - name: firefox.zip
      location: artifacts
      pattern: firefox.zip
      shared: true
      required: true
    - name: firefox.xpi
      location: artifacts
      pattern: firefox.xpi
      shared: true
      required: true
    - name: update.json
      location: artifacts
      pattern: update.json
      shared: true
      required: true
    - name: source.zip
      location: artifacts
      pattern: source.zip
      shared: true
      required: true
  requirements:
    - adg-docker: 'true'

triggers: []

branches:
  create: manually
  delete: never
  link-to-jira: 'true'

notifications:
  - events:
      - plan-status-changed
    recipients:
      - webhook:
          name: Build webhook
          url: http://prod.jirahub.service.eu.consul/v1/webhook/bamboo
labels: []
other:
  concurrent-build-plugin: system-default
