---
version: 2
plan:
  project-key: ADGEXT
  key: BEINCRSPECS
  name: browser extension - increment version
variables:
  dockerNode: adguard/extension-builder:22.17--0.3.0--0

stages:
  - Increment:
      manual: false
      final: false
      jobs:
        - Increment

Increment:
  key: INCR
  other:
    clean-working-dir: true
  docker:
    image: ${bamboo.dockerNode}
    volumes:
      ${system.PNPM_DIR}: "${bamboo.cachePnpm}"
  tasks:
    - checkout:
        force-clean-build: 'true'
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -x
            set -e

            # Fix mixed logs
            exec 2>&1

            ls -la

            # Set cache directory
            pnpm config set store-dir ${bamboo.cachePnpm}

            # Install deps for custom increment script
            pnpm install ${bamboo.varsPnpm}

            pnpm increment
    - any-task:
        plugin-key: com.atlassian.bamboo.plugins.vcs:task.vcs.commit
        configuration:
          commitMessage: 'skipci: Automatic increment build number'
          selectedRepository: defaultRepository
  final-tasks:
    - script:
        interpreter: SHELL
        scripts:
          - "./bamboo-specs/scripts/cleanup.sh"
  requirements:
    - extension: 'true'

branches:
  create: manually
  delete: never
  link-to-jira: 'true'

notifications: []
labels: []
other:
  concurrent-build-plugin: system-default
