---
version: 2
plan:
  project-key: ADGEXT
  key: BETESTSPECS
  name: browser extension - test
stages:
  - Build and test:
      manual: false
      final: false
      jobs:
        - Lint
        - Unit tests
        - Test dev build
        - Build chrome crx artifact
  - Integration tests:
      manual: false
      final: false
      jobs:
        - Integration tests

Test dev build:
  key: TESTDEVBUILD
  other:
    clean-working-dir: true
  tasks:
    - checkout:
        force-clean-build: true
    - script:
        interpreter: SHELL
        scripts:
          - |-
            # 'set' should be added to the beginning of each script to ensure that it runs with the correct options.
            #  -e: Exit immediately if any command exits with a non-zero status (i.e., if a command fails).
            #  -x: Print each command to the terminal as it is executed, which is useful for debugging.
            set -ex

            # Fix mixed logs
            exec 2>&1

            # Clone tsurlfilter to sibling directory (uses SSH from CI environment)
            ./bamboo-specs/scripts/clone-tsurlfilter.sh

            export DOCKER_BUILDKIT=1

            # Build with named context for tsurlfilter
            # Docker checksums the context content for cache invalidation
            docker build \
              --file Dockerfile \
              --progress plain \
              --build-arg TEST_RUN_ID=${bamboo.buildNumber} \
              --build-context tsurlfilter=../tsurlfilter \
              --target dev-build-output \
              --output type=local,dest=output \
              .
  # IMPORTANT: run clean after each job, since each job is run in a separate
  # directory and we want to clean up after each job.
  final-tasks:
    - script:
        interpreter: SHELL
        scripts:
          - "./bamboo-specs/scripts/cleanup.sh output/artifacts/build.txt,output/artifacts/chrome-dev.zip,output/artifacts/chrome-mv3-dev.zip,output/artifacts/edge-dev.zip,output/artifacts/firefox-amo-dev.zip,output/artifacts/firefox-standalone-dev.zip,output/artifacts/opera-dev.zip"
  artifacts:
    - name: build.txt
      location: output/artifacts
      pattern: build.txt
      required: true
    - name: chrome-dev.zip
      location: output/artifacts
      pattern: chrome-dev.zip
      required: true
    - name: chrome-mv3-dev.zip
      location: output/artifacts
      pattern: chrome-mv3-dev.zip
      required: true
      # Mark it shared to download from stages for tests
      shared: true
    - name: edge-dev.zip
      location: output/artifacts
      pattern: edge-dev.zip
      required: true
    - name: firefox-amo-dev.zip
      location: output/artifacts
      pattern: firefox-amo-dev.zip
      required: true
    - name: firefox-standalone-dev.zip
      location: output/artifacts
      pattern: firefox-standalone-dev.zip
      required: true
    - name: opera-dev.zip
      location: output/artifacts
      pattern: opera-dev.zip
      required: true
  requirements: &requirements
    - extension: 'true'

Build chrome crx artifact:
  key: BUILDCHROMECRX
  other:
    clean-working-dir: true
  tasks:
    - checkout:
        force-clean-build: true
    - script:
        interpreter: SHELL
        scripts:
          - |-
            # 'set' should be added to the beginning of each script to ensure that it runs with the correct options.
            #  -e: Exit immediately if any command exits with a non-zero status (i.e., if a command fails).
            #  -x: Print each command to the terminal as it is executed, which is useful for debugging.
            set -ex

            # Fix mixed logs
            exec 2>&1

            # Clone tsurlfilter to sibling directory (uses SSH from CI environment)
            ./bamboo-specs/scripts/clone-tsurlfilter.sh

            export DOCKER_BUILDKIT=1

            # Build with named context for tsurlfilter
            # Docker checksums the context content for cache invalidation
            docker build \
              --file Dockerfile \
              --progress plain \
              --build-arg TEST_RUN_ID=${bamboo.buildNumber} \
              --build-context tsurlfilter=../tsurlfilter \
              --target chrome-crx-output \
              --output type=local,dest=output \
              .
  final-tasks:
    - script:
        interpreter: SHELL
        scripts:
          - "./bamboo-specs/scripts/cleanup.sh output/artifacts/chrome-dev.crx"
  artifacts:
    - name: chrome-dev.crx
      location: output/artifacts
      pattern: chrome-dev.crx
      required: true
  requirements: *requirements

Lint:
  key: LINT
  other:
    clean-working-dir: true
  tasks:
    - checkout:
        force-clean-build: true
    - script:
        interpreter: SHELL
        scripts:
          - |-
            # 'set' should be added to the beginning of each script to ensure that it runs with the correct options.
            #  -e: Exit immediately if any command exits with a non-zero status (i.e., if a command fails).
            #  -x: Print each command to the terminal as it is executed, which is useful for debugging.
            set -ex

            # Fix mixed logs
            exec 2>&1

            # Clone tsurlfilter to sibling directory (uses SSH from CI environment)
            ./bamboo-specs/scripts/clone-tsurlfilter.sh

            export DOCKER_BUILDKIT=1

            # Build with named context for tsurlfilter
            # Docker checksums the context content for cache invalidation
            docker build \
              --file Dockerfile \
              --progress plain \
              --build-arg TEST_RUN_ID=${bamboo.buildNumber} \
              --build-context tsurlfilter=../tsurlfilter \
              --target lint-output \
              --output type=local,dest=output \
              .
  final-tasks:
    - script: &cleanup-script
        interpreter: SHELL
        scripts:
          - "./bamboo-specs/scripts/cleanup.sh"
  requirements: *requirements

Unit tests:
  key: UNITTESTS
  other:
    clean-working-dir: true
  tasks:
    - checkout:
        force-clean-build: true
    - script:
        interpreter: SHELL
        scripts:
          - |-
            # 'set' should be added to the beginning of each script to ensure that it runs with the correct options.
            #  -e: Exit immediately if any command exits with a non-zero status (i.e., if a command fails).
            #  -x: Print each command to the terminal as it is executed, which is useful for debugging.
            set -ex

            # Fix mixed logs
            exec 2>&1

            # Clone tsurlfilter to sibling directory (uses SSH from CI environment)
            ./bamboo-specs/scripts/clone-tsurlfilter.sh

            export DOCKER_BUILDKIT=1

            # Build with named context for tsurlfilter
            # Docker checksums the context content for cache invalidation
            docker build \
              --file Dockerfile \
              --progress plain \
              --build-arg TEST_RUN_ID=${bamboo.buildNumber} \
              --build-context tsurlfilter=../tsurlfilter \
              --target unit-tests-output \
              --output type=local,dest=output \
              .
    - script:
        interpreter: SHELL
        scripts:
          - |-
            if [ -f output/exit-code.txt ]; then
              exit $(cat output/exit-code.txt)
            fi
            echo "output/exit-code.txt not found"
            exit 1
  final-tasks:
    - test-parser:
        type: junit
        test-results: 'output/tests-reports/unit-tests-mv*.xml'
    - script: *cleanup-script
  requirements: *requirements

Integration tests:
  key: INTEGRATIONTESTS
  other:
    clean-working-dir: true
  tasks:
    - checkout:
        force-clean-build: true
    - artifact-download:
        artifacts:
          - name: chrome-mv3-dev.zip
    - script:
        interpreter: SHELL
        scripts:
          - |-
            # 'set' should be added to the beginning of each script to ensure that it runs with the correct options.
            #  -e: Exit immediately if any command exits with a non-zero status (i.e., if a command fails).
            #  -x: Print each command to the terminal as it is executed, which is useful for debugging.
            set -ex

            # Fix mixed logs
            exec 2>&1

            mkdir -p artifacts
            if [ -f chrome-mv3-dev.zip ]; then
              mv chrome-mv3-dev.zip artifacts/
            fi

            # Clone tsurlfilter to sibling directory (uses SSH from CI environment)
            ./bamboo-specs/scripts/clone-tsurlfilter.sh

            export DOCKER_BUILDKIT=1

            # Build with named context for tsurlfilter
            # Docker checksums the context content for cache invalidation
            docker build \
              --file Dockerfile \
              --progress plain \
              --build-arg TEST_RUN_ID=${bamboo.buildNumber} \
              --build-context tsurlfilter=../tsurlfilter \
              --target integration-tests-output \
              --output type=local,dest=output \
              .
    - script:
        interpreter: SHELL
        scripts:
          - |-
            if [ -f output/exit-code.txt ]; then
              exit $(cat output/exit-code.txt)
            fi
            echo "output/exit-code.txt not found"
            exit 1
  final-tasks:
    - test-parser:
        type: junit
        test-results: 'output/tests-reports/integration-tests-*.xml'
    - script: *cleanup-script
  requirements: *requirements

branches:
  create: for-pull-request
  delete:
    after-deleted-days: '1'
    after-inactive-days: '5'
  link-to-jira: true

notifications: []
labels: []
other:
  concurrent-build-plugin: system-default
