---
version: 2
plan:
  project-key: ADGEXT
  key: BETESTSPECS
  name: browser extension - test
variables:
  # playwright is needed for integration tests after build
  dockerNode: adguard/playwright-runner:22.14--1.51.1--0

stages:
  - Test build:
      manual: false
      final: false
      jobs:
        - Test build
  - Tests:
      manual: false
      final: false
      jobs:
        - Lint
        - Unit tests
        - Integration tests

Test build:
  key: TESTBUILD
  other:
    clean-working-dir: true
  docker:
    image: ${bamboo.dockerNode}
    volumes:
      ${system.PNPM_DIR}: "${bamboo.cachePnpm}"
  tasks:
    - checkout:
        force-clean-build: true
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -x
            set -e
            ls -la

            # Fix mixed logs
            exec 2>&1

            # Set cache directory
            pnpm config set store-dir ${bamboo.cachePnpm}

            pnpm install ${bamboo.varsPnpm}

            # Create artifacts directory if it doesn't exist
            mkdir -p artifacts

            # Run each target separately to identify from which firefox target
            # (firefox-standalone or firefox-amo) the zip 'firefox.zip' was created.

            # Add postfix to all zip files for easier identification target env.
            pnpm dev chrome
            mv build/dev/chrome.zip artifacts/chrome-dev.zip
            mv build/dev/chrome.crx artifacts/chrome-dev.crx

            pnpm dev chrome-mv3
            mv build/dev/chrome-mv3.zip artifacts/chrome-mv3-dev.zip

            pnpm dev edge
            mv build/dev/edge.zip artifacts/edge-dev.zip

            # TODO: (AG-41656) Remove this renaming when will start use the browser name for zip filename
            pnpm dev firefox-amo
            mv build/dev/firefox.zip artifacts/firefox-amo-dev.zip

            # TODO: (AG-41656) Remove this renaming when will start use the browser name for zip filename
            pnpm dev firefox-standalone
            mv build/dev/firefox-standalone.zip artifacts/firefox-standalone-dev.zip

            pnpm dev opera
            mv build/dev/opera.zip artifacts/opera-dev.zip

            mv build/dev/build.txt artifacts/
  final-tasks:
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -x
            set -e

            # Fix mixed logs
            exec 2>&1

            ls -la

            echo "Size before cleanup:" && du -h | tail -n 1
            rm -rf node_modules build
            echo "Size after cleanup:" && du -h | tail -n 1
  artifacts:
    - name: build.txt
      location: artifacts
      pattern: build.txt
      required: true
    - name: chrome-dev.zip
      location: artifacts
      pattern: chrome-dev.zip
      required: true
    - name: chrome-mv3-dev.zip
      location: artifacts
      pattern: chrome-mv3-dev.zip
      required: true
      # Mark it shared to download from stages for tests
      shared: true
    - name: chrome-dev.crx
      location: artifacts
      pattern: chrome-dev.crx
      required: true
    - name: edge-dev.zip
      location: artifacts
      pattern: edge-dev.zip
      required: true
    - name: firefox-amo-dev.zip
      location: artifacts
      pattern: firefox-amo-dev.zip
      required: true
    - name: firefox-standalone-dev.zip
      location: artifacts
      pattern: firefox-standalone-dev.zip
      required: true
    - name: opera-dev.zip
      location: artifacts
      pattern: opera-dev.zip
      required: true
  requirements:
    - adg-docker: 'true'

Lint:
  key: LINT
  other:
    clean-working-dir: true
  docker:
    image: ${bamboo.dockerNode}
    volumes:
      ${system.PNPM_DIR}: "${bamboo.cachePnpm}"
  tasks:
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -x
            set -e
            ls -la

            # Fix mixed logs
            exec 2>&1

            # Set cache directory
            pnpm config set store-dir ${bamboo.cachePnpm}

            pnpm install ${bamboo.varsPnpm}

            ./bamboo-specs/scripts/timeout-wrapper.sh 120s pnpm lint
  final-tasks:
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -x
            set -e

            # Fix mixed logs
            exec 2>&1

            ls -la

            echo "Size before cleanup:" && du -h | tail -n 1
            rm -rf node_modules build
            echo "Size after cleanup:" && du -h | tail -n 1
  requirements:
    - adg-docker: 'true'

Unit tests:
  key: UNITTESTS
  other:
    clean-working-dir: true
  docker:
    image: ${bamboo.dockerNode}
    volumes:
      ${system.PNPM_DIR}: "${bamboo.cachePnpm}"
  tasks:
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -x
            set -e
            ls -la

            # Fix mixed logs
            exec 2>&1

            # Set cache directory
            pnpm config set store-dir ${bamboo.cachePnpm}

            pnpm install ${bamboo.varsPnpm}

            ./bamboo-specs/scripts/timeout-wrapper.sh 300s pnpm test:ci
  final-tasks:
    - test-parser:
        type: junit
        test-results: 'tests-reports/unit-tests-mv*.xml'
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -x
            set -e

            # Fix mixed logs
            exec 2>&1

            ls -la

            echo "Size before cleanup:" && du -h | tail -n 1
            rm -rf node_modules build
            echo "Size after cleanup:" && du -h | tail -n 1
  requirements:
    - adg-docker: 'true'

Integration tests:
  key: INTEGRATIONTESTS
  other:
    clean-working-dir: true
  docker:
    image: ${bamboo.dockerNode}
    volumes:
      ${system.PNPM_DIR}: "${bamboo.cachePnpm}"
  tasks:
    - artifact-download:
        artifacts:
          - name: chrome-mv3-dev.zip
    - script:
        interpreter: SHELL
        scripts:
          - |-
            # Call the common script with timeout
            ./bamboo-specs/scripts/timeout-wrapper.sh 300s bash ./bamboo-specs/scripts/integration-tests.sh dev
  final-tasks:
    - test-parser:
        type: junit
        test-results: 'tests-reports/integration-tests-*.xml'
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -x
            set -e

            # Fix mixed logs
            exec 2>&1

            ls -la

            echo "Size before cleanup:" && du -h | tail -n 1
            rm -rf node_modules build
            echo "Size after cleanup:" && du -h | tail -n 1
  requirements:
    - adg-docker: 'true'

branches:
  create: for-pull-request
  delete:
    after-deleted-days: '1'
    after-inactive-days: '5'
  link-to-jira: true

notifications: []
labels: []
other:
  concurrent-build-plugin: system-default
