#!/bin/bash

# Reads a pre-generated exclude list and outputs `find`-compatible exclusion arguments.
#
# Preferred usage (with pre-generated excludes from generate-find-excludes.sh):
#   source parse-gitignore.sh gitignore-excludes.txt
#
# Fallback usage (parses .gitignore directly — only supports simple patterns):
#   source parse-gitignore.sh .gitignore
#
# Sets GITIGNORE_EXCLUDE_ARGS as a bash array with find-compatible exclusion patterns.
# No eval needed — use: find . -type f "${GITIGNORE_EXCLUDE_ARGS[@]}"

# Input file path. Defaults to gitignore-excludes.txt (generated by generate-find-excludes.sh).
DEFAULT_FILE="gitignore-excludes.txt"
INPUT_FILE="${1:-${DEFAULT_FILE}}"

GITIGNORE_EXCLUDE_ARGS=()

if [ -f "$INPUT_FILE" ]; then
  while IFS= read -r line; do
    # Skip empty lines and comments
    [ -z "$line" ] && continue
    case "$line" in \#*) continue;; esac
    # Skip negation patterns (lines starting with !)
    case "$line" in \!*) continue;; esac
    # Remove trailing slashes
    pattern="${line%/}"
    # For .gitignore fallback: strip wildcards for simple matching
    case "$pattern" in *\**) pattern="$(echo "$pattern" | tr -d '*')";; esac
    # Remove leading slashes (anchored patterns → relative)
    pattern="${pattern#/}"
    [ -n "$pattern" ] && GITIGNORE_EXCLUDE_ARGS+=("!" "-path" "./$pattern" "!" "-path" "./$pattern/*")
  done < "$INPUT_FILE"
fi
