(function () {
var _g = window._g;
if (!_g) return;
_g.r("remove-class", {"name":"remove-class","args":["active-brand","body"],"engine":"extension","version":"2.4.2","verbose":false}, ["active-brand","body"], "f4dfc7cfcee3c87948d38a4d7d2404d1");
_g.r("spoof-css", {"name":"spoof-css","args":["article[itemid] ~ article:not([itemid])","display","block"],"engine":"extension","version":"2.4.2","verbose":false}, ["article[itemid] ~ article:not([itemid])","display","block"], "20575c5badea9bf12baa17a57f93aacc");
_g.r("spoof-css", {"name":"spoof-css","args":["body > * > * > * > div[id][class]","display","block"],"engine":"extension","version":"2.4.2","verbose":false}, ["body > * > * > * > div[id][class]","display","block"], "25ea3f733bf858c686ee0e11414c865d");
_g.r("spoof-css", {"name":"spoof-css","args":["body > * > * > * > *:not(div)[id][class] ~ *:not(div)[id][class] > *:not(div)[class] article","height","149px"],"engine":"extension","version":"2.4.2","verbose":false}, ["body > * > * > * > *:not(div)[id][class] ~ *:not(div)[id][class] > *:not(div)[class] article","height","149px"], "05b593431a0eb578e8a475732b149dec");
_g.r("spoof-css", {"name":"spoof-css","args":["body > * > * > * > *:not(div)[id][class] ~ *:not(div)[id][class] > *:not(div)[class] article > article","display","block"],"engine":"extension","version":"2.4.2","verbose":false}, ["body > * > * > * > *:not(div)[id][class] ~ *:not(div)[id][class] > *:not(div)[class] article > article","display","block"], "608a05dd30583cadf9c55260a0ce89f8");
_g.r("spoof-css", {"name":"spoof-css","args":["body > * > * > * > *:not(div)[id][class] ~ *:not(div)[id][class] > *:not(div)[class] article","display","block"],"engine":"extension","version":"2.4.2","verbose":false}, ["body > * > * > * > *:not(div)[id][class] ~ *:not(div)[id][class] > *:not(div)[class] article","display","block"], "21b1da7577720e40d1b5fb4ce79fd98a");
_g.r("spoof-css", {"name":"spoof-css","args":["body > * > * > * > *:not(div)[id][class] ~ *:not(div)[id][class] [style^=\"overflow: hidden; height:\"] > *","display","block"],"engine":"extension","version":"2.4.2","verbose":false}, ["body > * > * > * > *:not(div)[id][class] ~ *:not(div)[id][class] [style^=\"overflow: hidden; height:\"] > *","display","block"], "45b2db56be65a44f28c5e1de582e9b40");
})();
