export const ANTIBANNER_FILTERS_ID = {
    USER_FILTER_ID: 0,
    RUSSIAN_FILTER_ID: 1,
    ENGLISH_FILTER_ID: 2,
    TRACKING_FILTER_ID: 3,
    SOCIAL_FILTER_ID: 4,
    SEARCH_AND_SELF_PROMO_FILTER_ID: 10,
    ALLOWLIST_FILTER_ID: 100,
    EASY_PRIVACY: 118,
    FANBOY_ANNOYANCES: 122,
    FANBOY_SOCIAL: 123,
    FANBOY_ENHANCED: 215,
    MOBILE_ADS_FILTER_ID: 11,
};
