#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# npx cross-env FORCE_COLOR=1 to enable colors in the output when running
# a command from husky just as if it were run manually from the terminal
npx cross-env FORCE_COLOR=1 pnpm lint-staged
