name: Tests Browser Extension

env:
  PNPM_VERSION: 10.7.1
  NODE_VERSION: 22.14.0
  # Forks do not have access to our vars
  VARS_PNPM: ${{ vars.VARS_PNPM || '--silent --ignore-scripts' }}

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v5
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://registry.npmjs.org
          cache: pnpm

      - name: pnpm install
        run: pnpm install ${{ env.VARS_PNPM }}

      - name: pnpm test
        run: pnpm test

  notify:
    needs: test
    # Run this job only if the previous job failed and the event was triggered from the original repository
    # Note: 'always()' is needed to run the notify job even if the test job was failed
    if:
      ${{
        always() &&
        needs.test.result == 'failure' &&
        github.repository == 'AdguardTeam/AdguardBrowserExtension' &&
        (
          github.event_name == 'push' ||
          github.event_name == 'workflow_dispatch' ||
          github.event.pull_request.head.repo.full_name == github.repository
        )
      }}
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack notification
        uses: slackapi/slack-github-action@v3
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            text: "❌ Tests failed"
            attachments:
              - color: "danger"
                fields:
                  - title: "Workflow"
                    value: "${{ github.workflow }}"
                    short: true
                  - title: "Repo"
                    value: "<${{ github.server_url }}/${{ github.repository }}|${{ github.repository }}>"
                    short: true
                  - title: "Message"
                    value: "${{ github.event.head_commit.message || format('Manual trigger by {0}', github.actor) }}"
                    short: false
                  - title: "Commit"
                    value: "<${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha }}>"
                    short: true
                  - title: "Author"
                    value: "${{ github.actor }}"
                    short: true
                  - title: "Event"
                    value: "${{ github.event_name }}"
                    short: true
                  - title: "Ref"
                    value: "${{ github.ref }}"
                    short: true
                  - title: "Job"
                    value: "test"
                    short: true
