/**
 * Copyright (c) 2015-2026 Adguard Software Ltd.
 *
 * @file
 * This file is part of AdGuard Browser Extension (https://github.com/AdguardTeam/AdguardBrowserExtension).
 *
 * AdGuard Browser Extension is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * AdGuard Browser Extension is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with AdGuard Browser Extension. If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * Type declaration for the virtual module resolved by the bundler at build time.
 * The actual file is generated by `pnpm resources:mv3` and injected via
 * `resolve.alias` in the Rspack configuration.
 */
declare module 'preregistered-scripts-registry' {
    /**
     * Registry of domains mapped to the filter IDs whose rules are bundled
     * as preregistered content scripts for that domain.
     */
    const preregisteredDomainScripts: Record<string, string[]>;

    export { preregisteredDomainScripts };
}
